# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mu_ind <- function(mu, y, l) {
    .Call(`_clusterCVR_mu_ind`, mu, y, l)
}

mu3_yvec <- function(mu, y) {
    .Call(`_clusterCVR_mu3_yvec`, mu, y)
}

choice_ind <- function(M, L) {
    .Call(`_clusterCVR_choice_ind`, M, L)
}

choice_set <- function(M) {
    .Call(`_clusterCVR_choice_set`, M)
}

mu3_yvec_vchoice <- function(mu, y, m) {
    .Call(`_clusterCVR_mu3_yvec_vchoice`, mu, y, m)
}

ll_vclogit_rcpp <- function(par, y_j, zeta_k, m_j) {
    .Call(`_clusterCVR_ll_vclogit_rcpp`, par, y_j, zeta_k, m_j)
}

grad_vclogit_rcpp <- function(par, y_j, zeta_k, m_j) {
    .Call(`_clusterCVR_grad_vclogit_rcpp`, par, y_j, zeta_k, m_j)
}

